"""Write scripts/p1_coupe_data.gd: the P1 sports coupe's stock design proxy
(docs/design/fleet/proxies.json, stage B1 as merged) packed as GDScript
constants, so the game builds the player's car from the exact shape on the
design sheet without parsing the 2.5 MB fleet file at boot.

    python game_export.py            # after godot_export.py

Positions are int16 millimetres, base64 (same packing as proxies.json);
material indices are uint8, base64. Colours are resolved per material name
the way tests/fleet_proxies.gd does it (car colours first, then the base
palette), so the builder needs nothing else.
"""
import json
import os
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', 'docs', 'design', 'fleet', 'proxies.json')
OUT = os.path.join(HERE, '..', '..', 'scripts', 'p1_coupe_data.gd')
CAR_ID = 'p1_coupe'
BUILD = 'stock'
CHUNK = 120


def color_of(mat, car, data):
    o = car['colors']
    if mat == 'paint':
        return o['paint']
    if mat == 'roof':
        return o['roof'] if o.get('roof') else o['paint']
    if o.get(mat):
        return o[mat]
    if mat == 'rim_bronze' and o.get('rim'):
        return o['rim']
    return data['mats'].get(mat) or '#C9CED6'


def gd_chunks(name, b64):
    lines = ['const %s := [' % name]
    for i in range(0, len(b64), CHUNK):
        lines.append('\t"%s",' % b64[i:i + CHUNK])
    lines.append(']')
    return '\n'.join(lines)


def main():
    with open(SRC) as f:
        data = json.load(f)
    car = next(c for c in data['cars'] if c['id'] == CAR_ID)
    b = next(x for x in car['builds'] if x['name'] == BUILD)
    names = b['names']
    colors = {n: color_of(n, car, data) for n in names}
    wheels = []
    for w in b['wheels']:
        wheels.append('\t{"hub": Vector3(%s, %s, %s), "tris": %d, "pos": "%s", "mat": "%s"},' % (
            w['hub'][0], w['hub'][1], w['hub'][2], int(w['tris']), w['pos'], w['mat']))
    slots = []
    for s in b['slots']:
        pl = ['{"center": Vector3(%s, %s, %s), "normal": Vector3(%s, %s, %s)}' % (
            tuple(p['center']) + tuple(p['normal'])) for p in s['placements'] if p]
        slots.append('\t{"id": "%s", "view": "%s", "mirror": %s, "note": "%s", "size": Vector2(%s, %s), "placements": [%s]},' % (
            s['id'], s['view'], 'true' if s['mirror'] else 'false', s['note'], s['size'][0], s['size'][1], ', '.join(pl)))
    tips = ['\t{"pos": Vector3(%s, %s, %s), "dir": Vector3(%s, %s, %s), "r": %s},' % (
        tuple(t['pos']) + tuple(t['dir']) + (t['r'],)) for t in b['tips']]
    body = '\n'.join([
        'extends RefCounted',
        '',
        '# GENERATED by tools/fleet_design/game_export.py from docs/design/fleet/proxies.json',
        '# (%s, %s build, stage B1 design sheet as merged). Do not edit by hand;' % (CAR_ID, BUILD),
        '# rerun the exporter after godot_export.py.',
        '#',
        '# Godot axes: X right, Y up, -Z forward. Origin on the ground, midway between',
        '# the axles. Positions are int16 millimetres, base64; material indices uint8,',
        '# base64; one material per triangle. Triangles are counter-clockwise seen',
        '# from outside (the builder flips them for Godot).',
        '',
        'const ID := "%s"' % CAR_ID,
        'const LABEL := "%s"' % car['label'],
        'const BUILD := "%s"' % BUILD,
        'const NAMES := %s' % json.dumps(names),
        'const COLORS := %s' % json.dumps(colors),
        'const EMISSIVE := %s' % json.dumps(data['emissive']),
        'const GLASS := %s' % json.dumps(data['glass']),
        'const BODY_TRIS := %d' % int(b['body']['tris']),
        'const TRIS_TOTAL := %d' % int(b['tris_total']),
        gd_chunks('BODY_POS', b['body']['pos']),
        gd_chunks('BODY_MAT', b['body']['mat']),
        '## FR, FL, RR, RL; positions are relative to the hub.',
        'const WHEELS := [',
        '\n'.join(wheels),
        ']',
        '## The 4 sticker slots (door is mirrored: 2 placements). Centre and outward',
        '## normal in car space, size in metres (width, height).',
        'const STICKER_SLOTS := [',
        '\n'.join(slots),
        ']',
        '## Stock exhaust tips: position, direction and radius, in car space.',
        'const EXHAUST_TIPS := [',
        '\n'.join(tips),
        ']',
        '',
        'static func b64(chunks: Array) -> String:',
        '\treturn "".join(chunks)',
        '',
    ])
    with open(OUT, 'w', newline='\n') as f:
        f.write(body)
    print(os.path.normpath(OUT), os.path.getsize(OUT), 'bytes; body tris', b['body']['tris'], 'total', b['tris_total'])


if __name__ == '__main__':
    main()
