"""Write docs/design/fleet/proxies.json: every car's design proxy (stock and
each example build) packed for Godot, so the Godot checks in tests/ can load
the exact shapes the sheets show without Python.

Per build:
  body    body + parts + lights, one material name per triangle
  wheels  4 wheels (FR, FL, RR, RL), each re-centred on its hub
  slots   the 3 sticker slots, every placement (mirrored doors give 2), with
          centre, outward normal and size
  tips    exhaust tips (position, direction, radius)

Positions are int16 millimetres, base64; material indices are uint8, base64.
"""
import base64
import json
import os

import numpy as np

import car
import cars
import options
import render
from geom import Mesh

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'docs', 'design', 'fleet', 'proxies.json')


def _b64_pos(tris):
    q = np.round(np.asarray(tris, float).reshape(-1, 3) * 1000).astype('<i2')
    return base64.b64encode(q.tobytes()).decode()


def _b64_idx(names, mats):
    idx = np.array([names.index(x) for x in mats], np.uint8)
    return base64.b64encode(idx.tobytes()).decode()


def _slot_placements(slot):
    out = []
    for tris in slot['tris']:
        if not tris:
            out.append(None)
            continue
        pts = np.array([p for t in tris for p in t])
        nrm = np.zeros(3)
        for a, b, c in tris:
            nrm += np.cross(b - a, c - a)
        nrm /= max(np.linalg.norm(nrm), 1e-9)
        cen = pts.mean(0)
        # outward: away from the car's centre (same rule as export.slot_info)
        ref = np.array([0.0, 0.6, cen[2] if slot['view'] in ('left', 'right') else 0.0])
        if np.dot(nrm, cen - ref) < 0:
            nrm = -nrm
        area = sum(0.5 * np.linalg.norm(np.cross(b - a, c - a)) for a, b, c in tris)
        out.append({'center': [round(float(v), 4) for v in cen],
                    'normal': [round(float(v), 4) for v in nrm],
                    'area': round(float(area), 4)})
    return out


def pack_build(D0, build):
    D = car.resolve(D0, build)
    m = car.build(D0, build)
    wm = car.CarModel(D)
    wm.mesh = Mesh()
    car.add_wheels(wm)
    n_w = len(wm.mesh.tris)
    tris = m.mesh.array()
    mats = list(m.mesh.mats)
    assert n_w % 4 == 0, (D0['id'], n_w)
    body_t, body_m = tris[:-n_w], mats[:-n_w]
    wheel_t, wheel_m = tris[-n_w:], mats[-n_w:]
    names = sorted(set(mats))
    per = n_w // 4
    wheels = []
    axle_z = m.meta['wheels']['axle_z']
    wh = D['wheel']
    for k in range(4):
        t = wheel_t[k * per:(k + 1) * per]
        ai, side = divmod(k, 2)
        track = wh['track'] if ai == 0 else wh.get('track_rear', wh['track'])
        hub = np.array([track / 2 * (1 if side == 0 else -1), wh['r'], axle_z[ai]])
        c = t.reshape(-1, 3).mean(0)
        assert np.linalg.norm(c[[0, 2]] - hub[[0, 2]]) < 0.2, (D0['id'], k, c, hub)
        wheels.append({'hub': [round(float(v), 4) for v in hub], 'pos': _b64_pos(t - hub),
                       'mat': _b64_idx(names, wheel_m[k * per:(k + 1) * per]), 'tris': per})
    slots = [{'id': s['id'], 'view': s['view'], 'mirror': s['mirror'], 'note': s['note'],
              'size': [round(abs(s['rect'][2] - s['rect'][0]), 3), round(abs(s['rect'][3] - s['rect'][1]), 3)],
              'placements': _slot_placements(s)} for s in m.meta['sticker_slots']]
    return {
        'names': names,
        'body': {'pos': _b64_pos(body_t), 'mat': _b64_idx(names, body_m), 'tris': len(body_t)},
        'wheels': wheels,
        'slots': slots,
        'tips': m.meta['exhaust_tips'],
        'drop': m.meta['drop'],
        'tris_total': len(tris),
    }


def main():
    data = {
        'note': 'Generated by tools/fleet_design/godot_export.py from cars.py + options.py. Do not edit by hand.',
        'coords': 'Godot axes: X right, Y up, -Z forward. Origin on the ground, midway between the axles. Units: metres.',
        'mats': render.BASE_MATS,
        'emissive': sorted(render.EMISSIVE),
        'glass': ['glass'],
        'cars': [],
    }
    for D in cars.FLEET:
        p = D['paint']
        colors = cars.colors_for(D)
        entry = {'id': D['id'], 'role': D['role'], 'label': D['label'], 'colors': colors,
                 'part_types': sorted({q['type'] for q in D.get('parts', [])}), 'builds': []}
        for name, b in [('stock', {})] + list(options.BUILDS.get(D['id'], {}).items()):
            g = pack_build(D, b)
            g['name'] = name
            g['options'] = b
            g['part_types'] = sorted({q['type'] for q in car.resolve(D, b).get('parts', [])})
            entry['builds'].append(g)
        data['cars'].append(entry)
        print(D['id'], [g['tris_total'] for g in entry['builds']], flush=True)
    with open(OUT, 'w') as f:
        json.dump(data, f, separators=(',', ':'))
    print(os.path.normpath(OUT), os.path.getsize(OUT), 'bytes')


if __name__ == '__main__':
    main()
